//
//  StartView.m
//  Charades
//
//  Created by Rene Candelier on 1/17/14.
//  Copyright (c) 2014 NovusMobile. All rights reserved.
//

#import "StartView.h"
#import "CharadesActionView.h"
#import "CharadesViewController.h"
#import "CharadesAppDelegate.h"
#import "SampleSheetViewController.h"
#import "NAModalSheet.h"
#import "Store.h"

@interface StartView ()<NAModalSheetDelegate>



@end

@implementation StartView
@synthesize PopUpForScore;
int counter=0;
int categoryCounter=0;
BOOL team = YES;
NSInteger randomAnswer;
- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        // Custom initialization
        
        //Set Counter to 0 for us to use the first item of the array
        counter = 0;
        
    }
    return self;
}

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    NSUserDefaults *tourViewShow = [NSUserDefaults standardUserDefaults];
    NSInteger tourShow = [tourViewShow integerForKey:@"tourView"];
    if (tourShow == 1) {
        self.tourView.hidden = FALSE;
        
    }
    [tourViewShow setInteger:2 forKey:@"tourView"];
    [[NSUserDefaults standardUserDefaults]synchronize];
	//Dispay what team is up team
    if (team){
        self.teamLabel.text = @"Team A";
    }else{self.teamLabel.text =@"Team B";}

    
   
    self.currentCategory.text = self.category;
    self.categories = [[NSMutableArray alloc] initWithObjects: @"Movies",@"Singers",@"Celebs",@"Shows",@"Random",nil];
    
    //Build Random array
    [self StartArray];
    //set the category we will use from the Category View
    categoryItem = self.resultArray;

   
   
}


-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
    if ([segue.identifier isEqualToString:@"StartPlay"])
    {
        //Send the item of the category and counter to the
        
        CharadesActionView *categoryController = segue.destinationViewController;
        categoryController.currentItem=self.CategoryLabel.text;
        categoryController.currentCategory = self.category;
        categoryController.whatTeamisUp=self.teamLabel.text;
    }
}



-(void) StartArray{

//Array with Category and Items
    self.showsCategory = @[ @"The Office",
                           @"Martin",
                            @"Lie to Me",
                            @"Pokemom",
    @"Scandal",@"The Blacklist",@"Dancing with the Stars",
    @"NCIS",
    @"Homeland",
    @"Sleepy Hollow",
    @"The Bachelorette",
    @"Under the Dome",
    @"America's Got Talent",
    @"Suits",
    @"True Blood",
    @"Arrested Development",
    @"Pretty Little Liars",
   @"Marvel's Agents of S.H.I.E.L.D.",
    @"MasterChef Junior",
    @"Mad Men",
    @"The Voice",
    @"Game of Thrones",
   @"Mom",
    @"Grey's Anatomy",
    @"The Originals",
    @"The Michael J. Fox Show",
    @"Once Upon a Time in Wonderland",
    @"Parenthood",
    @"The Millers",
    @"Person of Interest",
    @"The Big Bang Theory",
    @"Two and a Half Men",
    @"Chicago Fire",
    @"The Bachelor",
    @"The Following",
    @"Revolution",
    @"Reign",
    @"The Carrie Diaries",
    @"Vegas",
    @"Nashville",
    @"Arrow",
    @"The Amazing Race",
    @"Elementary",
    @"Hannibal",
    @"Modern Family",
    @"Parks and Recreation",
    @"Criminal Minds",
   @"Bones",
    @"Revenge",
    @"New Girl",
   @"Breaking Bad",
    @"Once Upon a Time",
    @"Glee",
    @"Keeping Up with the Kardashians",
    @"Justified",
   @" Castle",
    @"House of Cards",
    @"How I Met Your Mother",
    @"Community",
    @"The Vampire Diaries",
    @"One Life to Live",
    @"Sean Saves the World",
    @"Dexter",
    @"The Walking Dead",
   @" Nikita",
    @"Witches of East End",
    @"Bad Girls Club",
@"CSI",
    @"Super Fun Night",
                     @"Tomorrow People",
                     @"Trophy Wife",
                                  @"Brooklyn Nine-Nine",
                                  @"Days of Our Lives",
                                  @"Cold Justice",
                                  @"Secret Life of the American Teenager",
                                  @"The Americans",
                                  @"Hostages",
                                  @"Enlisted",
                                  @"The Goldbergs",
                                  @"All My Children",
                                  @"Hello Ladies",
                                  @"Welcome to the Family",
                                  @"Archer",
                                  @"Girls",
                                  @"House of Lies",
                                  @"Shameless",
                                  @"Smash",
                                  @"Masterpiece",
                                  @"Luther",
                                  @"Dracula",
                                  @"The Crazy Ones",
                                  @"Cougar Town",
                                  @"Dads",
                                  @"Bunheads",
                                  @"Psych",
                                  @"Almost Human",
                                  @"Necessary Roughness",
                                  @"White Collar",
                                  @"Alphas",
                                  @"Being Human",
                                 @" Betrayal",
                                 @" Anger Management",
                                 @" Dallas",
                                  @"Happy Endings",
                                  @"The Mindy Project",
                                  @"The Newsroom",
                                  @"Nurse Jackie",
                                  @"Portlandia",
                                  @"Project Runway",
                                  @"Saturday Night Live",
                                  @"Jimmy Kimmel Live",
                                  @"Colbert Report",
                                  @"The Daily Show With Jon Stewart",
                                  @"Spartacus",
                                  @"Southland",
                                  @"Hawaii Five 0",
                                  @"Grimm",
                                  @"iCarly",
                                  @"Supernatural",
                                  @"Californication",
                                  @"Family Guy",
                                  @"The Young and the Restless",
                                  @"Law & Order: Special Victims Unit",
                                  @"American Horror Story: Asylum",
                                  @"Fringe",
                                  @"The Mentalist",
                                  @"The Good Wife",
                                  @"Private Practice",
                                  @"Sons of Anarchy",
                                  @"Dr. Oz Show",
                            @"General Hospital",
                            @"The American Outdoorsman",
    @"Baseball Tonight",
    @"Changing Your World",
    @"Outside the Lines",
    @"Sunday Night Baseball",
    @"This is Your Day",
    @"Wednesday Night Baseball",
    @"Charlie Rose",
    @"E! News",
    @"The Jerry Springer Show",
    @"Maury",
    @"Notre Dame Football on NBC",
    @"Dateline NBC",
    @"HBO First Look",
    @"Money Talks News",
    @"The Real World",
    @"Reliable Sources",
    @"To the Contrary",
    @"Up to the Minute",
    @"Late Show with David Letterman",
    @"Monday Night Countdown",
    @"NFL Matchup",
    @"Off Beat Cinema",
    @"Power Rangers",
    @"Super Tuesday",
    @"The Weather Classroom",
    @"WWE Raw",
    @"Extra",
    @"Fox NFL Sunday",
    @"Globe Trekker",
    @"The Hal Lindsey Report",
    @"Inside the Actors Studio",
    @"NFL on Fox",
    @"Primer Impacto",
    @"VH1 Top 20 Video Countdown",
    @"Golf Central",
    @"Golf on TNT",
    @"The Late Late Show",
    @"Modern Marvels",
    @"Planet X Television",
    @"Squawk Box",
    @"Washington Journal",
    @"Wild About Animals",
    @"25 Days of Christmas",
    @"Access Hollywood",
    @"The American Athlete",
    @"Arthur",
    @"Boxing After Dark",
    @"The Daily Show",
    @"E! True Hollywood Story",
    @"Gold Fever",
    @"Hablemos de Salud",
    @"Judge Judy",
    @"Live from the Red Carpet",
    @"MSNBC Live",
    @"The O'Reilly Factor",
    @"Power Lunch",
    @"Street Signs",
    @"WWE Free for All",
    @"Animal Rescue",
    @"Antiques Roadshow",
    @"Autoline Detroit",
    @"¡Despierta América!",
    @"Enjoying Everyday Life",
    @"HGTV Dream Home",
    @"Movie Surfers",
    @"My Classic Car",
    @"The People's Court",
    @"South Park",
    @"SportsDay",
    @"SportsNite",
    @"SportsRise",
    @"The View",
    @"Book TV",
    @"The Challenge",
    @"El Gordo y la Flaca",
    @"Fox & Friends",
    @"Friday Night Fights",
    @"NFL Live",
    @"Pokémon",
    @"Pro Wrestling Report",
    @"True Life",
    @"Curb Appeal",
    @"Divorce Court",
    @"Early Today",
    @"Family Feud",
    @"Fox Report",
    @"The Greatest",
    @"Hardwood Classics",
    @"House Hunters",
    @"Independent Lens",
    @"Judge Mathis",
    @"Law & Order: Special Victims Unit",
    @"República Deportiva",
    @"SpongeBob SquarePants",
    @"Trucks!",
    @"Who Wants to Be a Millionaire",
    @"World of Playboy",
    @"WWE SmackDown",
    @"106 & Park",
    @"Aqua Kids",
    @"Aqua Teen Hunger Force",
    @"Big Brother",
    @"Blinkers Off",
    @"Burt Wolfe: Travels and Traditions",
    @"Cheaters",
    @"CSI: Crime Scene Investigation",
    @"Curb Your Enthusiasm",
    @"Dora the Explorer",
    @"In Depth",
    @"Morning Rush",
    @"P. Allen Smith Gardens",
    @"Secrets of the Dead",
    @"Solo boxeo",
    @"Survivor",
    @"The Amazing Race",
    @"America's Test Kitchen",
    @"The Cost of Freedom",
    @"GardenSMART",
    @"Hard Knocks",
    @"How It's Made",
    @"The John Kerwin Show",
    @"New Year's Eve Live",
    @"Pardon the Interruption",
    @"The Quarters",
    @"ShoBox: The New Generation",
    @"Two Guys Garage",
    @"Unwrapped",
    @"VH1's Top 40 Videos of the Year",
    @"Al Rojo Vivo",
    @"American Idol",
    @"Around the Horn",
    @"The Bachelor",
    @"Barefoot Contessa",
    @"Bulls & Bears",
    @"Campfire Café",
    @"Cashin' In",
    @"Caso Cerrado",
    @"Cavuto on Business",
    @"Closing Bell",
    @"CMT Crossroads",
    @"Contacto Deportivo",
    @"The Daily Buzz",
    @"The Dr. Phil Show",
    @"Forbes on Fox",
    @"Last Call with Carson Daly",
    @"Made",
    @"NBA Countdown",
    @"NBA Fastbreak",
    @"NBA Shootaround",
    @"NBA Wednesday",
    @"On the Record w/ Greta Van Susteren",
    @"Recipe TV Featuring the World's Greatest Chefs",
    @"Ritmo Deportivo",
    @"Shepard Smith Reporting",
    @"The Tim McCarver Show",
    @"TNA Xplosion",
    @"World Music",
    @"Yankeeography",
    @"Yankees Classics",
    @"Accion",
    @"America's Next Top Model",
    @"Anderson Cooper 360°",
    @"The Big Break",
    @"Bluegrass & Backroads",
    @"Comedy Central Roast",
    @"The Ellen DeGeneres Show",
    @"Fons and Porter's Love of Quilting",
    @"Headbangers Ball",
    @"History Detectives",
    @"Jimmy Kimmel Live!",
    @"Missing",
    @"MythBusters",
    @"NCIS",
    @"New Scandinavian Cooking",
    @"New Year's Eve with Carson Daly",
    @"NFL Scoreboard",
    @"NFL Total Access",
    @"¿Quién Tiene la Razón?",
    @"Simply Ming",
    @"Teen Kids News",
    @"Thursday Night Showcase",
    @"Two and a Half Men",
    @"Wednesday Night Hoops",
    @"ABC Saturday Movie of the Week",
    @"American Latino TV",
    @"Animal Atlas",
    @"The Apprentice",
    @"The Biggest Loser",
    @"Chop Cut Rebuild",
    @"Fearless Music",
    @"The First 48",
    @"Ghost Hunters",
    @"Gina D's Kids Club",
    @"Impact Wrestling",
    @"INN World Report",
    @"The Insider",
    @"In This Corner",
    @"Journal Editorial Report",
    @"LatiNation",
    @"MegaStructures",
    @"Mike & Mike",
    
    @"On the Water",
    @"Project Runway",
    @"Q&A",
    @"Snapped",
    @"The Soup",
    @"Tavis Smiley",
    @"Top 20 Country Countdown",
    @"Untold Stories of the E.R.",
    @"The Venture Bros.",
    @"Worldwide Day of Play",
    @"12 Corazones",
    @"After Words",
    @"All Around Performance Horse Weekly",
    @"America's Heartland",
    @"American Dad!",
    @"Art Mann Presents",
    @"Bones",
    @"The Boondocks",
    @"Bowhunter TV",
    @"The Colbert Report",
    @"Criminal Minds",
    @"Dancing with the Stars",
    @"Deadliest Catch",
    @"Deadly Women",
    @"Designing Spaces",
    @"Doctor Who",
    @"Family Guy",
    @"Food Network Star",
    @"Foreign Exchange",
    @"Geraldo at Large",
    @"Golf at Altitude",
    @"Good Night Show",
    @"Grey's Anatomy",
    @"Heartland Poker Tour",
    @"Hell's Kitchen",
    @"High School Showcase",
    @"How I Met Your Mother",
    @"Iron Chef America",
    @"It's Always Sunny in Philadelphia",
    @"Johnny Test",
    @"Judge Alex",
    @"Lockup",
    @"Mad Money",
    @"Made in Hollywood",
    @"Nancy Grace",
    @"NHL Live",
    @"Nitido",
    @"Nova ScienceNow",
    @"Puppy Bowl",
    @"Robot Chicken",
    @"Saturday Primetime",
    @"The Situation Room",
    @"So You Think You Can Dance",
    @"Squawk on the Street",
    @"Squidbillies",
    @"Supernatural",
    @"Titulares y Más",
    @"The Ultimate Fighter",
    @"X Games",
    @"Xtreme 4x4",
    @"31 Days of Oscar",
    @"America's Game: The Super Bowl Champions",
    @"America's Got Talent",
    @"Bad Girls Club",
    @"Bayly",
    @"CNN Newsroom",
    @"Curious George",
    @"Dallas Cowboys Cheerleaders: Making the Team",
    @"Dan Rather Reports",
    @"Diners, Drive-Ins and Dives",
    @"Fast Money",
    @"Future Phenoms",
    @"Guy's Big Bite",
    @"HGTV Star",
    @"House Smarts",
    @"Metalocalypse",
    @"Million Dollar Listing Los Angeles",
    @"Monday Night Live",
    @"Monster Madhouse Live",
    @"Movie and a Makeover",
    @"MSNBC Doc Block",
    @"MuscleCar",
    @"net IMPACT",
    @"NFL GameDay",
    @"Psych",
    @"The Rachael Ray Show",
    @"The Real Housewives of Orange County",
    @"SportsCenterU",
    @"Top Chef",
    @"Western Extreme",
    @"Whacked Out Sports",
    @"World Cup Live",
    @"Your Business",
    @"24/7",
    @"Al Punto",
    @"American Greed",
    @"BBC World News America",
    @"Better",
    @"The Big Bang Theory",
    @"Big Brother: After Dark",
    @"Business Nation",
    @"Californication",
    @"Chelsea Lately",
    @"CNN Heroes",
    @"CNN Presents",
    @"CNN Special Investigations Unit",
    @"College Football Live",
    @"Color Splash",
    @"Dog Tales",
    @"E:60",
    @"First Take",
    @"Flipping Out",
    @"HDNet Fights",
    @"Ice Road Truckers",
    @"Inside MMA",
    @"Jack Hanna's Into the Wild",
    @"Jail",
    @"Keeping Up with the Kardashians",
    @"Kitchen Nightmares",
    @"Mad Men",
    @"Man Caves",
    @"Markets Now",
    @"McDonald's Thanksgiving Parade",
    @"Morning Joe",
    @"The Next Iron Chef",
    @"NFL Top 10",
    @"NHL Tonight",
    @"Nuestra Belleza Latina",
    @"Path to the Draft",
    @"Phineas and Ferb",
    @"Ralph Emery Live",
    @"Red Eye w/Greg Gutfeld",
    @"Say Yes to the Dress",
    @"The Singing Bee",
    @"Source One Television",
    @"The Steve Wilkos Show",
    @"Sunday Best",
    @"The Sunny Side Up Show",
    @"Tekzilla",
    @"TMZ on TV",
    @"Ultimate Factories",
    @"The Universe",
    @"WordGirl",
    @"Yo Gabba Gabba!",
    @"19 Kids and Counting",
    @"After the First 48",
    @"Andrea Mitchell Reports",
    @"Ax Men",
    @"The Bachelorette",
    @"Beer Money!",
    @"Black Enterprise Business Report",
    @"Black Gold",
    @"Childrens Hospital",
    @"Cook's Country",
    @"Countdown to the Closing Bell",
    @"Crook & Chase",
    @"David Tutera: Unveiled",
    @"The Doctors",
    @"Fareed Zakaria GPS",
    @"Ghost Adventures",
    @"Giada at Home",
    @"Happening Now",
    @"Huckabee",
    @"I Survived...",
    @"Jane Velez-Mitchell",
    @"The Joe Girardi Show",
    @"Live from the Artists Den",
    @"Martha Speaks",
    @"The Mentalist",
    @"The Millionaire Matchmaker",
    @"Model Latina",
    @"My Generation",
    @"NASA 360",
    @"NBA.com Fantasy Insider",
    @"NBA Gametime Live",
    @"The Penguins of Madagascar",
    @"Planeta U",
    @"Primetime: What Would You Do?",
    @"The Rachel Maddow Show",
    @"The Rachel Zoe Project",
    @"The Real Housewives of Atlanta",
    @"The Real Housewives of New York City",
    @"Rip the Runway",
    @"Scare Tactics",
    @"Sons of Anarchy",
    @"Sprout Sharing Show",
    @"Superjail!",
    @"The Suze Orman Show",
    @"Tabatha Takes Over",
    @"That Metal Show",
    @"Total Drama",
    @"True Blood",
    @"TruTV Presents: World's Dumbest...",
    @"Un Nuevo Día",
    @"Unsung",
    @"Web Therapy",
    @"The Wendy Williams Show",
    @"Whale Wars",
    @"Wicked Attraction",
    @"Wipeout",
    @"WWE Vintage",
    @"16 and Pregnant",
    @"Alaska State Troopers",
    @"American Ninja Warrior",
    @"AMTV",
    @"Baseball's Seasons",
    @"BBQ Pitmasters",
    @"Behind the Music",
    @"Cake Boss",
    @"Car Crazy",
    @"Castle",
    @"Celebrity Ghost Stories",
    @"Chopped",
    @"Chronicle Live",
    @"The Clark Howard Show",
    @"CNN Newsroom",
    @"The Colony",
    @"Community",
    @"Cougar Town",
    @"The Dan Patrick Show",
    @"Dear Genevieve",
    @"The Dr. Oz Show",
    @"Drop Dead Diva",
    @"Eco Company",
    @"The Ed Show",
    @"The Fresh Beat Band",
    @"Full Throttle Saloon",
    @"Giuliana and Bill",
    @"Glee",
    @"The Good Wife",
    @"Hannity",
    @"Headline Country",
    @"Hot Stove",
    @"IShine KNECT",
    @"Kevin Pollak's Chat Show",
    @"The Kudlow Report",
    @"The League",
    @"Let's Make a Deal, CBS Daytime version",
    @"The Little Couple",
    @"The Middle",
    @"Midnight Monster Hop",
    @"MLB Tonight",
    @"Modern Family",
    @"Monsters Inside Me",
    @"NCIS: Los Angeles",
    @"Nurse Jackie",
    @"Parks and Recreation",
    @"Pawn Stars",
    @"Pit Bulls & Parolees",
    @"Police Women",
    @"Quick Pitch",
    @"The Real Housewives of New Jersey",
    @"Rob Dyrdek's Fantasy Factory",
    @"Royal Pains",
    @"RuPaul's Drag Race",
    @"Shark Tank",
    @"SportsNation",
    @"Steven Seagal: Lawman",
    @"Stossel",
    @"Toddlers & Tiaras",
    @"Top Chef Masters",
    @"Tosh.0",
    @"Tough Love",
    @"UFC Primetime",
    @"The Vampire Diaries",
    @"Warehouse 13",
    @"Watch What Happens Live",
    @"Way Too Early",
    @"Weather Center Live",
    @"Weekend Marketplace",
    @"White Collar",
    @"The Winemakers",
    @"WWE Superstars",
    @"Adventure Time",
    @"America Now",
    @"American Pickers",
    @"American Restoration",
    @"Ancient Aliens",
    @"Archer",
    @"Ariel & Zoey & Eli, Too",
    @"Auction Hunters",
    @"Auction Kings",
    @"The Aviators",
    @"Basketball Wives",
    @"The Big Help",
    @"Blue Bloods",
    @"Boardwalk Empire",
    @"Border Wars",
    @"Championship Wrestling from Hollywood",
    @"Conan",
    @"Covert Affairs",
    @"Cupcake Wars",
    @"The Daily Rundown",
    @"Drugs, Inc.",
    @"Dual Survival",
    @"Education Station",
    @"Family Game Night",
    @"Fashion Police",
    @"Fish Hooks",
    @"Fuse Top 20 Countdown",
    @"Gold Rush",
    @"The Great Food Truck Race",
    @"Hardcore Pawn",
    @"Haven",
    @"Hawaii Five-0",
    @"Hoarding: Buried Alive",
    @"Hot in Cleveland",
    @"I (Almost) Got Away With It",
    @"I Hate My Kitchen",
    @"Inside E Street",
    @"Jansing and Company",
    @"Jersey Couture",
    @"Jerseylicious",
    @"John Oliver's New York Stand-Up Show",
    @"Justified",
    @"Louie",
    @"Love That Girl!",
    @"Maltin on Movies",
    @"Masterclass",
    @"MasterChef",
    @"Master of the Mix",
    @"Melissa & Joey",
    @"Mike & Molly",
    @"MMA Live",
    @"My Ghost Story",
    @"My Little Pony: Friendship Is Magic",
    @"My Strange Addiction",
    @"Next Great Baker",
    @"NFL Rush Zone: Guardians of the Core",
    @"Oddities",
    @"Parenthood",
    @"Pretty Little Liars",
    @"R. L. Stine's The Haunting Hour",
    @"Raising Hope",
    @"The Real Housewives of Beverly Hills",
    @"Regular Show",
    @"Rescue Renovation",
    @"The Rich Eisen Podcast",
    @"Rizzoli & Isles",
    @"Rookie Blue",
    @"Sanjay Gupta MD",
    @"Say Yes to the Dress: Atlanta",
    @"Selling New York",
    @"Sister Wives",
    @"Storage Wars",
    @"The Talk",
    @"Team Umizoomi",
    @"Through the Wormhole",
    @"Top Gear",
    @"Top Shot",
    @"Undercover Boss",
    @"Unique Eats",
    @"Unusual Suspects",
    @"The Vanilla Ice Project",
    @"The Walking Dead",
    @"Who Do You Think You Are?",
    @"Wild Justice",
    @"Worst Cooks in America",
    @"WWE NXT",
    @"The Young Icons",
    @"2 Broke Girls",
    @"36",
    @"After Lately",
    @"The Amazing World of Gumball",
    @"American Hoggers",
    @"American Horror Story",
    @"A.N.T. Farm",
    @"Austin & Ally",
    @"Awkward.",
    @"Bar Rescue",
    @"Behind Mansion Walls",
    @"Being Human",
    @"Beyond Scared Straight",
    @"Big Rich Texas",
    @"The Bill Cunningham Show",
    @"Bob's Burgers",
    @"Braxton Family Values",
    @"Bubble Guppies",
    @"The Chew",
    @"Dance Moms",
    @"The Dead Files",
    @"Dr. Drew On Call",
    @"Eagleheart",
    @"Elizabeth Stanton's Great Big World",
    @"Episodes",
    @"Erin Burnett OutFront",
    @"The Exes",
    @"Extreme Weight Loss",
    @"Face Off",
    @"Falling Skies",
    @"Feherty",
    @"Finding Bigfoot",
    @"The First 48: Missing Persons",
    @"The Five",
    @"The Franchise",
    @"Franklin & Bash",
    @"Game of Thrones",
    @"Gigolos",
    @"Golf Channel on NBC",
    @"Grimm",
    @"Hard Time",
    @"Hart of Dixie",
    @"Hell on Wheels",
    @"Highly Questionable",
    @"Homeland",
    @"Impractical Jokers",
    @"Intentional Talk",
    @"Jake and the Never Land Pirates",
    @"Jessie",
    @"Joan & Melissa: Joan Knows Best?",
    @"Just Josh",
    @"Kickin' It",
    @"Kitchen Boss",
    @"Kung Fu Panda: Legends of Awesomeness",
    @"Last Man Standing",
    @"Let's Stay Together",
    @"Litton's Weekend Adventure",
    @"Lizard Lick Towing",
    @"Long Island Medium",
    @"The Looney Tunes Show",
    @"Love & Hip Hop",
    @"Mob Wives",
    @"My Cat from Hell",
    @"NCAA March Madness",
    @"New Girl",
    @"On the Spot",
    @"Once Upon a Time",
    @"Oprah's Lifeclass",
    @"Oprah's Master Class",
    @"Paranormal Witness",
    @"Person of Interest",
    @"Piers Morgan Live",
    @"Pop-Up Video",
    @"Portlandia",
    @"Redakai: Conquer the Kairu",
    @"Restaurant: Impossible",
    @"Revenge",
    @"Right This Minute",
    @"Shameless",
    @"Single Ladies",
    @"SkyWeek",
    @"Sons of Guns",
    @"South Beach Tow",
    @"Storage Hunters",
    @"Storage Wars: Texas",
    @"The Stream",
    @"Suburgatory",
    @"Suits",
    @"Surprising Europe",
    @"Sweet Genius",
    @"Switched at Birth",
    @"Talking Dead",
    @"Tanked",
    @"Teen Wolf",
    @"Too Cute",
    @"Tyler Perry's For Better or Worse",
    @"UFC on Fox",
    @"Unforgettable",
    @"Up",
    @"The Voice",
    @"Web Therapy",
    @"Welcome to Sweetie Pie's",
    @"Wild Kratts",
    @"Wilfred",
    @"Workaholics",
    @"6 Little McGhees",
    @"Abby's Ultimate Dance Competition",
    @"Airport 24/7: Miami",
    @"Amanpour",
    @"The American Bible Challenge",
    @"American Digger",
    @"Amish Mafia",
    @"Anger Management",
    @"The Aquabats! Super Show!",
    @"Arrow",
    @"Baby Daddy",
    @"Barter Kings",
    @"Be the Boss",
    @"Beauty & the Beast",
    @"Ben 10: Omniverse",
    @"Bering Sea Gold",
    @"Best Ink",
    @"Betty White's Off Their Rockers",
    @"Black Dynamite",
    @"Breaking Amish",
    @"Brickleberry",
    @"Cajun Pawn Stars",
    @"Cartoon Planet",
    @"Catfish: The TV Show",
    @"Caught Red Handed",
    @"CBS This Morning",
    @"CFL on NBC",
    @"The Chica Show",
    @"Chicago Fire",
    @"Comedy Bang! Bang!",
    @"Comic Book Men",
    @"Crash & Bernstein",
    @"The Cycle",
    @"Dallas",
    @"Daniel Tiger's Neighborhood",
    @"DC Nation",
    @"DC Nation Shorts",
    @"Dish Nation",
    @"Doc McStuffins",
    @"Doomsday Preppers",
    @"Dragons: Riders of Berk",
    @"Duck Dynasty",
    @"Early Start",
    @"Elementary",
    @"The First Family",
    @"Flea Market Flip",
    @"Fox & Friends First",
    @"Gator Boys",
    @"Girls",
    @"Gravity Falls",
    @"A Haunting",
    @"Here Comes Honey Boo Boo",
    @"Holliston",
    @"Hotel Hell",
    @"Hotel Impossible",
    @"House of Lies",
    @"Ink Master",
    @"Inside Comedy",
    @"It's a Brad, Brad World",
    @"Iyanla: Fix My Life",
    @"Katie",
    @"Kendra on Top",
    @"Key & Peele",
    @"Killer Karaoke",
    @"L.A. Hair",
    @"Lab Rats",
    @"The Legend of Korra",
    @"Lego Ninjago: Masters of Spinjitzu",
    @"Let's Ask America",
    @"The 'Lights",
    @"Littlest Pet Shop",
    @"Live! with Kelly and Michael",
    @"Lives of Style",
    @"Loiter Squad",
    @"Longmire",
    @"Love & Hip Hop: Atlanta",
    @"Marie",
    @"Married to Jonas",
    @"Mary Mary",
    @"Melissa Harris-Perry",
    @"Men at Work",
    @"Mike the Knight",
    @"Million Dollar Listing New York",
    @"The Mindy Project",
    @"MLS on NBC",
    @"Monsuno",
    @"Moyers & Company",
    @"Mr. Box Office",
    @"Mystery Diners",
    @"Nashville",
    @"The Neighbors",
    @"The Newsroom",
    @"Noticias MundoFox",
    @"Now in America",
    @"The Octonauts",
    @"Oh Sit!",
    @"Oprah's Next Chapter",
    @"Oprah: Where Are They Now?",
    @"Overhaulin",
    @"Perception",
    @"The Pitch",
    @"Property Wars",
    @"Push Girls",
    @"Rachael vs. Guy: Celebrity Cook-Off",
    @"Randy Cunningham: 9th Grade Ninja",
    @"Redneck Island",
    @"Revolution",
    @"Scandal",
    @"Sea Rescue",
    @"See Dad Run",
    @"Shahs of Sunset",
    @"Shipping Wars",
    @"Small Town Security",
    @"Snooki & Jwoww",
    @"The Soul Man",
    @"Steve Harvey",
    @"Sugar Dome",
    @"Sullivan & Son",
    @"Teenage Mutant Ninja Turtles",
    @"Total Blackout",
    @"Toy Hunter",
    @"Transporter: The Series",
    @"The Trisha Goddard Show",
    @"UFC Ultimate Insider",
    @"Ultimate Spider-Man",
    @"Veep",
    @"Wife Swap",
    @"Wild Grinders",
    @"The Wonderful World of Disney",
    @"WWE Main Event",
    @"Yu-Gi-Oh!",
    @"60 Minutes Sports",
    @"72 Hours",
    @"Almost Human",
    @"Alpha Dogs",
    @"The American Baking Competition",
    @"The Americans",
    @"America's Worst Tattoos",
    @"Are You Tougher Than a Boy Scout?",
    @"Armed & Ready",
    @"The Arsenio Hall Show",
    @"AwesomenessTV",
    @"Backyard Oil",
    @"Bad Girls All-Star Battle",
    @"Bad Ink",
    @"Banshee",
    @"Bates Motel",
    @"Belle's",
    @"Below Deck",
    @"Bethenny",
    @"Beware the Batman",
    @"The Big Brain Theory",
    @"Big Tips Texas",
    @"The Birthday Boys",
    @"Blackboard Wars",
    @"Black Ink Crew",
    @"The Blacklist",
    @"Blade Brothers",
    @"Bobby's Dinner Battle",
    @"Bounty Hunters",
    @"Breaking Amish: Brave New World",
    @"The Bridge",
    @"Brooklyn Nine-Nine",
    @"Burger Land",
    @"Capture",
    @"The Car Chasers",
    @"Car Lot Rescue",
    @"The Carrie Diaries",
    @"Cash Dome",
    @"Casino Confidential",
    @"Cedar Cove",
    @"Criss Angel BeLIEve",
    @"Continuum",
    @"Courtney Loves Dallas",
    @"The Crazy Ones",
    @"Crossing Lines",
    @"Crowd Goes Wild",
    @"Cutthroat Kitchen",
    @"Dads",
    @"Da Vinci's Demons",
    @"DC Cupcakes: County Fair",
    @"Deal with It",
    @"Deep South Paranormal",
    @"Defiance",
    @"Devious Maids",
    @"Does Someone Have to Go?",
    @"Dog and Beth: On the Hunt",
    @"Doomsday Castle",
    @"Double Divas",
    @"Dracula",
    @"Drunk History",
    @"Emeril's Florida",
    @"Exit",
    @"The Face",
    @"Failosophy",
    @"The Fairly OddParents",
    @"Fangasm",
    @"Fashion Queens",
    @"Find Me My Man",
    @"Flip or Flop",
    @"The Following",
    @"Food Court Wars",
    @"Food Factory",
    @"Foodiculous",
    @"Forecasting the End",
    @"Forever Young",
    @"The Fosters",
    @"Freakshow",
    @"Funeral Boss",
    @"Garage Gold",
    @"Generation Cryo",
    @"Getting On",
    @"Girl Code",
    @"Giving You The Business",
    @"Gizmodo: The Gadget Testers",
    @"God, Guns & Automobiles",
    @"The Goldbergs",
    @"The Governor's Wife",
    @"Graceland",
    @"Ground Floor",
    @"Guinness World Records Gone Wild",
    @"Guntucky",
    @"Gypsy Sisters",
    @"Hannibal",
    @"Hardcore Pawn: Chicago",
    @"The Haunted Hathaways",
    @"The Haves and the Have Nots",
    @"The Heart, She Holler",
    @"Hello Ross",
    @"Hemlock Grove",
    @"Henry Hugglemonster",
    @"The Hero",
    @"Heroes of Cosplay",
    @"Hollywood Game Night",
    @"Hostages",
    @"House of Cards",
    @"Ice Cold Gold",
    @"I Dream of NeNe: The Wedding",
    @"I Hate My Yard",
    @"Inside Amy Schumer",
    @"Inside Combat Rescue",
    @"Instant Mom",
    @"Joe Rogan Questions Everything",
    @"The Joe Schmo Show",
    @"Karma's A B*tch",
    @"Ke$ha: My Crazy Beautiful Life",
    @"Killer Contact",
    @"The Killer Speaks",
    @"King of the Nerds",
    @"Kirstie",
    @"Kroll Show",
    @"L.A. Frock Stars",
    @"LA Shrinks",
    @"The Legend of Shelby the Swamp Man",
    @"Legit",
    @"Loaded",
    @"Love Thy Neighbor",
    @"Mac Miller and the Most Dope Family",
    @"Maron",
    @"Marriage Boot Camp",
    @"Married to Medicine",
    @"Marvel's Agents of S.H.I.E.L.D.",
    @"Marvel's Avengers Assemble",
    @"Marvel's Hulk and the Agents of S.M.A.S.H.",
    @"MasterChef Junior",
    @"Masters of Sex",
    @"The Michael J. Fox Show",
    @"The Millers",
    @"The Million Second Quiz",
    @"Miss U Much",
    @"Mistresses",
    @"Mom",
    @"Monsters and Mysteries in America",
    @"Monumental Mysteries",
    @"Morgan Spurlock: Inside Man",
    @"Motive",
    @"Mountain Movers",
    @"Naked and Afraid",
    @"Nathan For You",
    @"The New Atlanta",
    @"New Day",
    @"Newlyweds: The First Year",
    @"Off Pitch",
    @"OK!TV",
    @"Olbermann",
    @"Once Upon a Time in Wonderland",
    @"Orange Is the New Black",
    @"The Originals",
    @"Orphan Black",
    @"Owner's Manual",
    @"Panic Button",
    @"Paternity Court",
    @"PAW Patrol",
    @"Perfect Score",
    @"The Pete Holmes Show",
    @"Peter Rabbit",
    @"Pizza Cuz",
    @"Pretty Wicked Moms",
    @"Princesses: Long Island",
    @"Property Envy",
    @"The Queen Latifah Show",
    @"Rabbids Invasion",
    @"Raising Whitley",
    @"Ray Donovan",
    @"The Real",
    @"Real Husbands of Hollywood",
    @"Rectify",
    @"Red White & New",
    @"Reign",
    @"Rescue My Renovations",
    @"Restaurant Express",
    @"Robot Combat League",
    @"Rogue",
    @"Sam & Cat",
    @"Sanjay and Craig",
    @"Scrubbing In",
    @"The Sheards",
    @"Shipwreck Men",
    @"The Show with Vinny",
    @"The Sing-Off",
    @"Sleepy Hollow",
    @"Sofia the First",
    @"Something Borrowed, Something New",
    @"The Soup Investigates",
    @"Splash",
    @"Steven Universe",
    @"Storage Wars: New York",
    @"Stroumboulopoulos",
    @"Styled to Rock",
    @"Super Fun Night",
    @"Supermarket Superstar",
    @"Swamp Pawn",
    @"Take Me to Your Mother",
    @"The Taste",
    @"Taste in Translation",
    @"The Test",
    @"Thicker Than Water: The Tankards",
    @"The Thundermans",
    @"Tickle",
    @"The Tomorrow People",
    @"Top Hooker",
    @"Total Divas",
    @"Treasure Detectives",
    @"Treehouse Masters",
    @"Trophy Wife",
    @"Trust Me, I'm a Game Show Host",
    @"Twisted",
    @"Ultimate Survival Alaska",
    @"Uncle Grandpa",
    @"Under the Dome",
    @"Upload with Shaquille O'Neal",
    @"Urban Tarzan",
    @"Vanderpump Rules",
    @"Vikings",
    @"The Vineyard",
    @"Wander Over Yonder",
    @"Weed Country",
    @"Welcome to Myrtle Manor",
    @"Whodunnit?",
    @"Who Gets the Last Laugh?",
    @"Whose Line Is It Anyway?",
    @"Wild Deep",
    @"Witches of East End",
    @"The Wonderful World of Stu",
    @"The Writers' Room",
    @"Your Pretty Face Is Going to Hell",
    @"100 Days of Summer",
    @"About a Boy",
    @"Beat the House",
    @"Bitten",
    @"Black Sails",
    @"Blood, Sweat & Heels",
    @"Breadwinners",
    @"Broad City",
    @"Chicago PD",
    @"Chozen",
    @"Enlisted",
    @"Game of Arms",
    @"Growing Up Fisher",
    @"Helix",
    @"I Didn't Do It",
    @"Inside Job",
    @"Intelligence",
    @"Kim of Queens",
    @"Late Night with Seth Meyers",
    @"Looking",
    @"Mind Games",
    @"Mind of a Man",
    @"Opposite Worlds",
    @"Private Lives of Nashville Wives",
    @"Rake",
    @"The Red Road",
    @"Ronan Farrow Daily",
    @"Southern Charm",
    @"Star-Crossed",
    @"Those Who Kill",
    @"Toned Up",
    @"The Tonight Show Starring Jimmy Fallon",
    @"True Detective",
    @"Wahlburgers",
    @"When Calls the Heart",
    @"Win, Lose or Draw",
    @"Kate Middleton"];
    
    
    
    
    
    
    
    self.celebsCategory = [[NSMutableArray alloc] initWithObjects: @"Will Smith",@"Indiana Jones",@"Darth Vader",@"Barbie"
    @"Eddie Albert",
    @"Robert Alda",
    @"Jane Alexander",
    @"Jason Alexander",
    @"Woody Allen",
    @"Don Ameche",
    @"Julie Andrews",
    @"Ann Margret",
    @"Beatrice Arthur",
    @"Ed Asner",
    @"Fred Astaire",
    @"Lauren Bacall",
    @"Anne Bancroft",
    @"John Barrymore",
    @"Warren Beatty",
    @"Bonnie Bedelia",
    @"Pat Benatar",
    @"Tony Bennett",
    @"Jack Benny",
    @"Robbie Benson",
    @"Ingmar Bergman",
    @"Milton Berle",
    @"Irving Berlin",
    @"Joey Bishop",
    @"Robert Blake",
    @"Jon Bon jovi",
    @"Bono",
    @"Sonny Bono",
    @"Pat Boone",
    @"Victor Borge",
    @"Chef Boyardee",
    @"David Bowie",
    @"Max Brand",
    @"Beau Bridges",
    @"Charles Bronson",
    @"Albert Brooks",
    @"Mel Brooks",
    @"Yul Brynner",
    @"George Burns",
    @"Ellen Burstyn",
    @"Richard Burton",
    @"Nicolas Cage",
    @"Michael Caine",
    @"Maria Callas",
    @"Dyan Cannon",
    @"Kate Capshaw",
    @"Vikki Carr",
    @"Diahann Carroll",
    @"Ray Charles",
    @"Charo",
    @"Chevy Chase",
    @"Chubby Checker",
    @"Cher",
    @"Eric Clapton",
    @"Patsey Cline",
    @"Lee J. Cobb",
    @"Perry Como",
    @"Bert Convy",
    @"Alice Cooper",
    @"David Copperfield",
    @"Howard Cosell",
    @"Elvis Costello",
    @"Joan Crawford",
    @"Bing Crosby",
    @"Tom Cruise",
    @"Tony Curtis",
    @"Rodney Dangerfield",
    @"Doris Day",
    @"Sandra Dee",
    @"John Denver",
    @"Bo Derek",
    @"Danny DeVito",
    @"Susan Dey",
    @"Marlene Dietrich",
    @"Phyllis Diller",
    @"Kirk Douglas",
    @"Mike Douglas",
    @"Patty Duke",
    @"Faye Dunaway",
    @"Bob Dylan",
    @"Sheena Easton",
    @"Buddy Ebsen",
    @"Barbara Eden",
    @"Edge",
    @"Mama Cass Elliot",
    @"Elvira",
    @"Werner Erhard",
    @"Dale Evans",
    @"Chad Everett",
    @"Douglas Fairbanks",
    @"Morgan Fairchild",
    @"Mia Farrow",
    @"Farrah Fawcett",
    @"Sally Field",
    @"W.C. Fields",
    @"Dame Margot Fonteyn",
    @"Glenn Ford",
    @"John Forsythe",
    @"Jodie Foster",
    @"Michael J. Foxx",
    @"Redd Foxx",
    @"Anthony Franciosa",
    @"Connie Francis",
    @"Carlton Fredericks",
    @"Fresh Prince",
    @"Greta Garbo",
    @"Ava Gardner",
    @"Judy Garland",
    @"James Garner",
    @"Crystal Gayle",
    @"Boy George",
    @"Barry Gibb",
    @"Whoopi Goldberg",
    @"Cary Grant",
    @"Lee Grant",
    @"Peter Graves",
    @"Joel Grey",
    @"Robert Guillaume",
    @"Buddy Hackett",
    @"Halston",
    @"Hammer",
    @"Rex Harrison",
    @"Laurence Harvey",
    @"Helen Hayes",
    @"Margaux Hemingway",
    @"Audrey Hepburn",
    @"Pee Wee Herman",
    @"Barbara Hershey",
    @"William Holden",
    @"Billie Holiday",
    @"Bob Hope",
    @"Harry Houdini",
    @"Rock Hudson",
    @"Engelbert Humperdinck",
    @"Mary Beth Hurt",
    @"Lauren Hutton",
    @"Billy Idol",
    @"Wolfman Jack",
    @"Elton John",
    @"Don Johnson",
    @"Al Jolson",
    @"Tom Jones",
    @"Louis Jourdan",
    @"Boris Karloff",
    @"Danny Kaye",
    @"Diane Keaton",
    @"Michael Keaton",
    @"Chaka Khan",
    @"Larry King",
    @"Ben Kingsley",
    @"Nastassia Kinski",
    @"Ted Knight",
    @"Kreskin",
    @"Cheryl Ladd",
    @"Bert Lahr",
    @"Ann Landers",
    @"Michael Landon",
    @"Stan Laurel",
    @"Piper Laurie",
    @"Steve Lawrence",
    @"Bruce Lee",
    @"Gypsy Rose Lee",
    @"Peggy Lee",
    @"Spike Lee",
    @"Huey Lewis",
    @"Jerry Lewis",
    @"Shari Lewis",
    @"Liberace",
    @"Hal Linden",
    @"Meat Loaf",
    @"Sophia Loren",
    @"Peter Lorre",
    @"Myrna Loy",
    @"Bela Lugosi",
    @"Andie MacDowell",
    @"Shirley MacLaine",
    @"Madonna",
    @"Lee Majors",
    @"Karl Malden",
    @"Jayne Mansfield",
    @"Fredric March",
    @"Dean Martin",
    @"Chico Marx",
    @"Groucho Marx",
    @"Harpo Marx",
    @"Zeppo Marx",
    @"Walter Matthau",
    @"Ethel Merman",
    @"Paul McCartney",
    @"Steve McQueen",
    @"George Michael",
    @"Joni Mitchell",
    @"Marilyn Monroe",
    @"Yves Montand",
    @"Demi Moore",
    @"Rita Moreno",
    @"Pat Morita",
    @"Zero Mostel",
    @"Ricky Nelson",
    @"Mike Nichols",
    @"Stevie Nicks",
    @"Chuck Norris",
    @"Kim Novak",
    @"Annie Oakley",
    @"Hugh O'Brian",
    @"Tony Orlando",
    @"Peter O'Toole",
    @"Jack Palance",
    @"Jane Pauley",
    @"Minnie Pearl",
    @"Gregory Peck",
    @"Bernadette Peters",
    @"Christopher Pike",
    @"Stephanie Powers",
    @"Paula Prentiss",
    @"Priscilla Presley",
    @"William Proxmire",
    @"Tony Randall",
    @"Robert Redford",
    @"Donna Reed",
    @"Della Reese",
    @"Judge Reinhold",
    @"Lee Remick",
    @"Debbie Reynolds",
    @"Edward G. Robinson",
    @"Ginger Rogers",
    @"Roy Rogers",
    @"Mickey Rooney",
    @"Theresa Russell",
    @"Buffy Sainte-Marie",
    @"Susan Saint James",
    @"Soupy Sales",
    @"Susan Sarandon",
    @"Leo Sayer",
    @"John Saxon",
    @"Jane Seymour",
    @"Omar Sharif",
    @"Artie Shaw",
    @"Charlie Sheen",
    @"Brooke Shields",
    @"Talia Shire",
    @"Dinah Shore",
    @"Beverly Sills",
    @"lone Skye",
    @"Phoebe Snow",
    @"Suzanne Somers",
    @"Elke Sommer",
    @"Ann Sothern",
    @"Sissy Spacek",
    @"Robert Stack",
    @"Sylvester Stallone",
    @"Jean Stapleton",
    @"Ringo Starr",
    @"Cat Stevens",
    @"Connie Stevens",
    @"Sting",
    @"Sly Stone",
    @"Meryl Streep",
    @"Donna Summer",
    @"Max von Sydow",
    @"Mr. T",
    @"Rip Taylor",
    @"Robert Taylor",
    @"Danny Thomas",
    @"Tiny Tim",
    @"Lily Tomlin",
    @"Rip Torn",
    @"Randy Travis",
    @"Tina Turner",
    @"Twiggy",
    @"Rudolph Valentino",
    @"Rudy Vallee",
    @"Abigail Van Buren",
    @"Nancy Walker",
    @"Mike Wallace",
    @"Andy Warhol",
    @"Muddy Waters",
    @"John Wayne",
    @"Sigourney Weaver",
    @"Raquel Welch",
    @"Tuesday Weld",
    @"Gene Wilder",
    @"Bruce Willis",
    @"Flip Wilson",
    @"Debra Winger",
    @"Shelley Winters",
    @"Stevie Wonder",
    @"Natalie Wood",
    @"Jane Wyman",
    @"Tammy Wynette",
    @"Ed Wynn",
    @"Loretta Young",
    @"Sean Young",
    @"Naomi Watts",
    @"Angelina Jolie",
    @"Megan Fox",
    @"Franco Nero",
    @"Peter Billingsley",
    @"Jason London",
    @"Ron Jeremy",
    @"George Pal",
    @"Patricia Arquette",
    @"Selena Gomez",
    @"Vincent D'Onofrio",
    @"Matt Damon",
    @"Jennifer Lopez",
    @"Shia LaBeouf",
    @"Marisa Tomei",
    @"Seth Rogen",
    @"Robert Redford",
    @"Jennifer Lawrence",
    @"Tom Hanks",
    @"Justin Bieber",
    @"James Caviezel",
    @"Bill Murray",
    @"Charlie Sheen",
    @"Catherine Zeta-Jones",
    @"Kelly Lynch",
    @"Kristen Stewart",
    @"Ben Affleck",
    @"Jeremy Renner",
    @"Brad Pitt",
    @"Ashley Judd",
    @"Jason Schwartzman",
    @"Robert De Niro",
    @"Jude Law",
    @"Natalya Rudakova",
    @"Jason Bateman",
    @"Jennifer Aniston",
    @"Johnny Depp",
    @"Gabriel Macht",
    @"John Malkovich",
    @"Channing Tatum",
    @"Amanda Seyfried",
    @"Mary-Louise Parker",
    @"Mark Harmon",
    @"Bradley Cooper",
    @"Christina Aguilera",
    @"Jason Statham",
    @"Sarah Jessica Parker",
    @"Jessica Alba",
    @"Stacey Dash",
    @"Paige Simpson",
    @"Will Ferrell",
    @"Gemma Arterton",
    @"Sylvester Stallone",
    @"Miley Cyrus",
    @"Vince Vaughn",
    @"Leonardo DiCaprio",
    @"Golshifteh Farahani",
    @"Tommy Lee Jones",
    @"Angelu DeLeon",
    @"Philip Seymour Hoffman",
    @"George Clooney",
    @"Justin Timberlake",
    @"Kathleen Turner",
    @"Martin Sheen",
    @"Nicole Kidman",
    @"Skylar Astin",
    @"Bruce Willis",
    @"Scarlett Johansson",
    @"Mickey Rourke",
    @"Roman Coppola",
    @"Denzel Washington",
    @"Danny Trejo",
    @"Adam Sandler",
    @"Chris Hemsworth",
    @"Matthew McConaughey",
    @"Famke Janssen",
    @"Lucas Black",
    @"Kim Kardashian",
    @"Tom Cruise",
    @"Eddie Murphy",
    @"Ron Howard",
    @"Jennifer Garner",
    @"Robert Pattinson",
    @"Christopher Waltz",
    @"Beyonce Knowles",
    @"Lindsay Lohan",
    @"Jeananne Goossen",
    @"Emily Mortimer",
    @"Jane Fonda",
    @"Meryl Streep",
    @"Tom Hardy",
    @"Wesley Snipes",
    @"Sean Penn",
    @"Paul Rudd",
    @"Zooey Deschanel",
    @"Jessica Chastain",
    @"Emma Thompson",
    @"Viola Davis",
    @"Maksim Vitorgan",
                           @"Sarah Shahi",nil];
    
    
    
    self.randomCategories = [[NSMutableArray alloc] initWithObjects: @"Frog",@"Dog",@"Lion",@"TV",@"Adult",
    @"Aeroplane",
    @"Air",
    @"Aircraft Carrier",
    @"Airforce",
    @"Airport",
    @"Album",
    @"Alphabet",
    @"Apple",
    @"Arm",
    @"Army",
    @"Baby",
    @"Baby",
    @"Backpack",
    @"Balloon",
    @"Banana",
    @"Bank",
    @"Barbecue",
    @"Bathroom",
    @"Bathtub",
    @"Bed",
    @"Bee",
    @"Bible",
    @"Bird",
    @"Bomb",
    @"Book",
    @"Boss",
    @"Bottle",
    @"Bowl",
    @"Box",
    @"Boy",
    @"Brain",
    @"Bridge",
    @"Butterfly",
    @"Button",
    @"Cappuccino",
    @"Car",
    @"Car-race",
    @"Carpet",
    @"Carrot",
    @"Cave",
    @"Chair",
    @"Chess Board",
    @"Chief",
    @"Child",
    @"Chisel",
    @"Chocolates",
    @"Church",
    @"Circle",
    @"Circus",
    @"Clock",
    @"Clown",
    @"Coffee",
    @"Coffee-shop",
    @"Comet",
    @"Compact Disc",
    @"Compass",
    @"Computer",
    @"Crystal",
    @"Cup",
    @"Cycle",
    @"Data Base",
    @"Desk",
    @"Diamond",
    @"Dress",
    @"Drill",
    @"Drink",
    @"Drum",
    @"Dung",
    @"Ears",
    @"Earth",
    @"Egg",
    @"Electricity",
    @"Elephant",
    @"Eraser",
    @"Explosive",
    @"Eyes",
    @"Family",
    @"Fan",
    @"Feather",
    @"Festival",
    @"Film",
    @"Finger",
    @"Fire",
    @"Floodlight",
    @"Flower",
    @"Foot",
    @"Fork",
    @"Freeway",
    @"Fruit",
    @"Fungus",
    @"Game",
    @"Garden",
    @"Gas",
    @"Gate",
    @"Gemstone",
    @"Girl",
    @"Gloves",
    @"God",
    @"Grapes",
    @"Guitar",
    @"Hammer",
    @"Hat",
    @"Hieroglyph",
    @"Highway",
    @"Horoscope",
    @"Horse",
    @"Hose",
    @"Ice",
    @"Ice-cream",
    @"Insect",
    @"Jet fighter",
    @"Junk",
    @"Kaleidoscope",
    @"Kitchen",
    @"Knife",
    @"Leather jacket",
    @"Leg",
    @"Library",
    @"Liquid",
    @"Magnet",
    @"Man",
    @"Map",
    @"Maze",
    @"Meat",
    @"Meteor",
    @"Microscope",
    @"Milk",
    @"Milkshake",
    @"Mist",
    @"Money",
    @"Monster",
    @"Mosquito",
    @"Mouth",
    @"Nail",
    @"Navy",
    @"Necklace",
    @"Needle",
    @"Onion",
    @"PaintBrush",
    @"Pants",
    @"Parachute",
    @"Passport",
    @"Pebble",
    @"Pendulum",
    @"Pepper",
    @"Perfume",
    @"Pillow",
    @"Plane",
    @"Planet",
    @"Pocket",
    @"Post-office",
    @"Potato",
    @"Printer",
    @"Prison",
    @"Pyramid",
    @"Radar",
    @"Rainbow",
    @"Record",
    @"Restaurant",
    @"Rifle",
    @"Ring",
    @"Robot",
    @"Rock",
    @"Rocket",
    @"Roof",
    @"Room",
    @"Rope",
    @"Saddle",
    @"Salt",
    @"Sandpaper",
    @"Sandwich",
    @"Satellite",
    @"School",
    @"Ship",
    @"Shoes",
    @"Shop",
    @"Shower",
    @"Signature",
    @"Skeleton",
    @"Slave",
    @"Snail",
    @"Software",
    @"Solid",
    @"Space Shuttle",
    @"Spectrum",
    @"Sphere",
    @"Spice",
    @"Spiral",
    @"Spoon",
    @"Sports-car",
    @"Spot Light",
    @"Square",
    @"Staircase",
    @"Star",
    @"Stomach",
    @"Sun",
    @"Sunglasses",
    @"Surveyor",
    @"Swimming Pool",
    @"Sword",
    @"Table",
    @"Tapestry",
    @"Teeth",
    @"Telescope",
    @"Television",
    @"Tennis racquet",
    @"Thermometer",
    @"Tiger",
    @"Toilet",
    @"Tongue",
    @"Torch",
    @"Torpedo",
    @"Train",
    @"Treadmill",
    @"Triangle",
    @"Tunnel",
    @"Typewriter",
    @"Umbrella",
    @"Vacuum",
    @"Vampire",
    @"Videotape",
    @"Vulture",
    @"Water",
    @"Weapon",
    @"Web",
    @"Wheelchair",
    @"Window",
    @"Woman",
    @"Worm",
    @"X-ray",
    @"Sausage",
    @"Blubber",
    @"Pencil",
    @"Cloud",
    @"Moon",
    @"Water",
    @"Computer",
    @"School",
    @"Network",
    @"Hammer",
    @"Walking",
    @"Violently",
    @"Mediocre",
    @"Literature",
    @"Chair",
    @"Two",
    @"Window",
    @"Cords",
    @"Musical",
    @"Zebra",
    @"Xylophone",
    @"Penguin",
    @"Home",
    @"Dog",
    @"Final",
    @"Ink",
    @"Teacher",
    @"Fun",
    @"Website",
    @"Banana",
    @"Uncle",
    @"Softly",
    @"Mega",
    @"Ten",
    @"Awesome",
    @"Attatch",
    @"Blue",
    @"Internet",
    @"Bottle",
    @"Tight",
    @"Zone",
    @"Tomato",
    @"Prison",
    @"Hydro",
    @"Cleaning",
    @"Send",
    @"Frog",
    @"Cup",
    @"Book",
    @"Zooming",
    @"Falling",
    @"Evily",
    @"Gamer",
    @"Lid",
    @"Juice",
    @"Moniter",
    @"Captain",
    @"Bonding",
    @"Loudly",
    @"Thudding",
    @"Guitar",
    @"Shaving",
    @"Hair",
    @"Soccer",
    @"Water",
    @"Racket",
    @"Table",
    @"Late",
    @"Media",
    @"Desktop",
    @"Flipper",
    @"Club",
    @"Flying",
    @"Smooth",
    @"Monster",
    @"Purple",
    @"Guardian",
    @"Bold",
    @"Hyperlink",
    @"Presentation",
    @"World",
    @"National",
    @"Comment",
    @"Element",
    @"Magic",
    @"Lion",
    @"Sand",
    @"Crust",
    @"Toast",
    @"Jam",
    @"Hunter",
    @"Forest",
    @"Foraging",
    @"Silently",
    @"Tawesomated",
    @"Joshing",
    @"Pong",nil];
    
    
    self.singersCategory = [[NSMutableArray alloc] initWithObjects:
                          @"50 Cent",
                          @"A-Ha",
                          @"Aaliyah",
                          @"Aaron Carter",
                          @"Abba",
                          @"Ac Dc",
                          @"Ace Of Base",
                          @"Adele",
                          @"Aerosmith",
                          @"Alanis Morissette",
                          @"Alex Band",
                          @"Alex Gaskarth",
                          @"Alicia Keys",
                          @"Alicja Bachleda Curus",
                          @"Alizee",
                          @"All Saints",
                          @"Amelle Berrabah",
                          @"Amy Grant",
                          @"Anastacia",
                          @"Andrea Corr",
                          @"Angel Faith",
                          @"Annie Lennox",
                          @"Aretha Franklin",
                          @"Ashanti",
                          @"Ashlee Simpson",
                          @"Ashley Tisdale",
                          @"Atomic Kitten",
                          @"Avril Lavigne",
                          @"Adam Levine",
                          @"Ayumi Hamasaki",
                          @"B-Witched",
                          @"Backstreet Boys",
                          @"Baha Men",
                          @"Barenaked Ladies",
                          @"Barry Manilow",
                          @"Beastie Boys",
                          @"Beatles",
                          @"Bee Gees",
                          @"Belinda Carlisle",
                          @"Beyonce",
                          @"Billie Piper",
                          @"Billy Idol",
                          @"Bing Crosby",
                          @"Bjork",
                          @"Blackstreet",
                          @"Black Eyed Peas",
                          @"Black Sabbath",
                          @"Blink 182",
                          @"Blondie",
                          @"Blu Cantrell",
                          @"Blur",
                          @"Bob Dylan",
                          @"Bob Marley",
                          @"Bon Jovi",
                          @"Brandy",
                          @"Brian Harvey",
                          @"Britney Spears",
                          @"Brooke Hogan",
                          @"Bryan Adams",
                          @"Bryan Ferry",
                          @"Busted",
                          @"Celine Dion",
                          @"Charlotte Church",
                          @"Cher Lloyd",
                          @"Cheryl Tweedy",
                          @"Christina Aguilera",
                          @"Christina Grimmie",
                          @"Christina Milian",
                          @"Christina Perri",
                          @"Cliff Richard",
                          @"Coldplay",
                          @"Corey Hart",
                          @"Craig David",
                          @"Cyndi Lauper",
                          @"Daniel Bedingfield",
                          @"Dannii Minogue",
                          @"Darkness",
                          @"Darren Hayes",
                          @"David Bowie",
                          @"David Gray",
                          @"Dean Martin",
                          @"Delta Goodrem",
                          @"Demi Lovato",
                          @"Depeche Mode",
                          @"Destinys Child",
                          @"Dido",
                          @"Dixie Chicks",
                          @"Dolores O'Riordan",
                          @"Don Henley",
                          @"Duncan James",
                          @"Elton John",
                          @"Elvis Presley",
                          @"Eminem",
                          @"Emma Bunton",
                          @"Emily Osment",
                          @"Enrique Iglesias",
                          @"Erasure",
                          @"Eric Clapton",
                          @"Eurythmics",
                          @"Evanescence",
                          @"Faith Hill",
                          @"Faith No More",
                          @"Fat Joe",
                          @"Fatboy Slim",
                          @"Faye Tozer",
                          @"Fiona Apple",
                          @"Framing Hanley",
                          @"Flobots",
                          @"Flo Rider",
                          @"Fleetwood Mac",
                          @"Foo Fighters",
                          @"Foxy Brown",
                          @"Frankee",
                          @"Frankie G T Hollywood",
                          @"Franz Ferdinand",
                          @"Fred Durst",
                          @"Fun Lovin Criminals",
                          @"Garbage",
                          @"Gareth Gates",
                          @"Garth Brooks",
                          @"Genesis",
                          @"George Harrison",
                          @"George Michael",
                          @"Geri Halliwell",
                          @"Girls Aloud",
                          @"Gloria Estefan",
                          @"Gloria Trevi",
                          @"Good Charlotte",
                          @"Green Day",
                          @"Groove Armada",
                          @"G-Unit",
                          @"Guns N Roses",
                          @"Gwen Stefani",
                          @"Hannah Spearritt",
                          @"Hanson",
                          @"Hinder",
                          @"Harry Connick Jr",
                          @"Heather Headley",
                          @"Heidi Range",
                          @"Hilary Duff",
                          @"Holly Valance",
                          @"Hoobastank",
                          @"Hope",
                          @"Ice Cube",
                          @"Ice T",
                          @"Idlewild",
                          @"Indigo Girls",
                          @"INXS",
                          @"Jamelia",
                          @"James Blunt",
                          @"James Brown",
                          @"Jamiroquai",
                          @"Janet Jackson",
                          @"Ja Rule",
                          @"Javine",
                          @"Jay-Z",
                          @"Jentina",
                          @"Jennifer Lopez",
                          @"Jesse McCartney",
                          @"Jessica Simpson",
                          @"Jewel Kilcher",
                          @"Jim Morrison",
                          @"Jimi Hendrix",
                          @"Joe Jonas",
                          @"John Lennon",
                          @"Jojo",
                          @"Joss Stone",
                          @"Justin Bieber",
                          @"Justin Timberlake",
                          @"K. T. Tunstall",
                          @"Kat DeLuna",
                          @"Kate Nash",
                          @"Katharine McPhee",
                          @"Katie Melua",
                          @"Katy Perry",
                          @"Keane",
                          @"Keisha Buchanan",
                          @"Keith Duffy",
                          @"Kelly Clarkson",
                          @"Kerry McFadden",
                          @"Ke$ha",
                          @"Kid Rock",
                          @"Kimberley Walsh",
                          @"Korn",
                          @"Kylie Minogue",
                          @"Lady Gaga",
                          @"Laura Pausini",
                          @"LeAnn Rimes",
                          @"Lenny Kravitz",
                          @"Leona Lewis",
                          @"Liberty X",
                          @"Lil Kim",
                          @"Limp Bizkit",
                          @"Linkin Park",
                          @"Lionel Richie",
                          @"Lisa Scott Lee",
                          @"Lisa Stansfield",
                          @"LL Cool J",
                          @"Lonestar",
                          @"Louise Redknapp",
                          @"Lucie Silvas",
                          @"Ludacris",
                          @"Luther Vandross",
                          @"McFly",
                          @"Macy Gray",
                          @"Madonna",
                          @"Mandy Moore",
                          @"Manic Street Preachers",
                          @"Mariah Carey",
                          @"Marilyn Manson",
                          @"Maroon 5",
                          @"Marvin Gaye",
                          @"Matchbox Twenty",
                          @"Meat Loaf",
                          @"Megadeth",
                          @"Mel B",
                          @"Mercury Rev",
                          @"Meredith Brooks",
                          @"Metal",
                          @"Michael Jackson",
                          @"Michelle Branch",
                          @"Michelle Heaton",
                          @"Mick Hucknall",
                          @"Miley Cyrus",
                          @"Mis-Teeq",
                          @"Missy Elliott",
                          @"Mitchel Musso",
                          @"Moby",
                          @"Morrissey",
                          @"Motley Crue",
                          @"Motorhead",
                          @"Mutya Buena",
                          @"Myleene Klass",
                          @"Nadine Coyle",
                          @"Natalie Appleton",
                          @"Natalie Imbruglia",
                          @"Natasha Bedingfield",
                          @"Nelly",
                          @"Nelly Furtado",
                          @"N.E.R.D.",
                          @"Nick Jonas",
                          @"Nickelback",
                          @"Nicky Byrne",
                          @"Nicola Roberts",
                          @"Nicole Appleton",
                          @"Nicole Scherzinger",
                          @"Nina Sky",
                          @"Nirvana",
                          @"No Doubt",
                          @"Norah Jones",
                          @"Notorious BIG",
                          @"NSync",
                          @"Oasis",
                          @"Offspring",
                          @"Otis Redding",
                          @"Outkast",
                          @"Ozzy Osbourne",
                          @"Papa Roach",
                          @"Patrick Stump",
                          @"Paul McCartney",
                          @"Paul Weller",
                          @"Paula Abdul",
                          @"Paulina Rubio",
                          @"Peter Andre",
                          @"Pilar Montenegro",
                          @"P!nk",
                          @"Pink Floyd",
                          @"Placebo",
                          @"Puff Daddy",
                          @"Pussycat Dolls",
                          @"Queen",
                          @"Queen Latifah",
                          @"Rachel Stevens",
                          @"Randy Travis",
                          @"Raquelle Gracie",
                          @"Rasmus",
                          @"Red Hot C. P.",
                          @"REM",
                          @"Richard Ashcroft",
                          @"Ricky Martin",
                          @"Rihanna",
                          @"R Kelly",
                          @"Robbie Williams",
                          @"Rod Stewart",
                          @"Rolling Stones",
                          @"Roxette",
                          @"Run DMC",
                          @"Sade",
                          @"Samantha Mumba",
                          @"Santana",
                          @"Sarah Brightman",
                          @"Sarah Harding",
                          @"Savage Garden",
                          @"Scissor Sisters",
                          @"S Club 7",
                          @"Sean Paul",
                          @"Selena",
                          @"Selena Gomez",
                          @"Sex Pistols",
                          @"Shaggy",
                          @"Shakira",
                          @"Shania Twain",
                          @"Sharleen Spiteri",
                          @"Sheryl Crow",
                          @"Simple Minds",
                          @"Simple Plan",
                          @"Siobhan Donaghy",
                          @"Sisqo",
                          @"Sisse Soby",
                          @"Slayer",
                          @"Smashing Pumpkins",
                          @"Snoop Dogg",
                          @"Snow Patrol",
                          @"Sophie Ellis Bextor",
                          @"Sophie Monk",
                          @"Spice Girls",
                          @"Stacey Ferguson",
                          @"Steve Brookstein",
                          @"Stevie Wonder",
                          @"Sting",
                          @"Stone Roses",
                          @"Sugababes",
                          @"Susanna Hoffs",
                          @"Tammin Sursok",
                          @"Tata Young",
                          @"Tatu",
                          @"The 411",
                          @"The Streets",
                          @"Thin Lizzy",
                          @"Tim McGraw",
                          @"Tina Arena",
                          @"Tina Turner",
                          @"TLC",
                          @"Taio Cruz",
                          @"Taylor Swift",
                          @"Three Days Grace",
                          @"Theory Of A Deadman",
                          @"Timbaland",
                          @"The Ting Tings",
                          @"Train",
                          @"Trey Songz",
                          @"Toby Keith",
                          @"Tom Jones",
                          @"Trisha Yearwood",
                          @"Toni Braxton",
                          @"Tori Amos",
                          @"Travis",
                          @"Tupac Shakur",
                          @"U2",
                          @"UB40",
                          @"Uncle Kracker",
                          @"Usher",
                          @"Van Halen",
                          @"Van Morrison",
                          @"Vanessa Carlton",
                          @"Vanessa Hudgens",
                          @"Vanessa Mae",
                          @"Vanessa Paradis",
                          @"Vanessa Williams",
                          @"Vengaboys",
                          @"Wayne Wonder",
                          @"Weezer",
                          @"Wendy James",
                          @"Westlife",
                          @"White Stripes",
                          @"Whitney Houston",
                          @"Will Young",
                          @"Willa Ford",
                          @"Willie Nelson",
                          @"Wu Tang Clan",
                          @"Wyclef Jean",
                          @"Xzibit",
                          @"Zac Efron",
                          @"ZZ Top",
    @"Paula Abdul",
    @"Eric Adams",
    @"Carrie Akre",
    @"Mariska Aldrich",
    @"Mary Alessi",
    @"Art Alexakis",
    @"Chet Allen",
    @"Donna Allen",
    @"Trey Anastasio",
    @"John Anderson",
    @"Signe Toly Anderson",
    @"Keith Andes",
    @"Paul Anka",
    @"Fiona Apple",
    @"Billie Joe Armstrong",
    @"Louis Armstrong",
    @"Lucie Arnaz",
    @"Martina Arroyo",
    @"Jasmine Ash",
    @"Audrey Assad",
    @"Patti Austin",
    @"Frankie Avalon",
    @"Chet Baker",
    @"Alex Band",
    @"Richard Barone",
    @"Mabel Barrison",
    @"Toni Basil",
    @"Lance Bass",
    @"Beck",
    @"Molly Bee",
    @"Pat Benatar",
    @"Harold Harper Bennett",
    @"Tony Bennett",
    @"Chester Bennington",
    @"Jodi Benson",
    @"Chuck Berry",
    @"Ken Berry",
    @"Beyoncé",
    @"Andy Biersack",
    @"Bobby Bland",
    @"Ken Block",
    @"Jon Bon Jovi",
    @"Chaz Bono",
    @"Jenn Bostic",
    @"Charles Bradley",
    @"Laura Bravo",
    @"Bray",
    @"Anne Bredon",
    @"Danielle Brisebois",
    @"Chris Taylor Brown",
    @"James Brown",
    @"Sleepy Brown",
    @"Aaron Bruno",
    @"Anita Bryant",
    @"Jeff Buckley",
    @"Bebe Buell",
    @"Paul Butterfield",
    @"Cage",
    @"JJ Cale",
    @"Mariah Carey",
    @"Aaron Carter",
    @"Leslie Carter",
    @"Nick Carter",
    @"Daniel Cartier",
    @"Jean Chapel",
    @"Cher",
    @"Vic Chesnutt",
    @"C cont.",
    @"Judy Clark",
    @"George Clinton",
    @"Kurt Cobain",
    @"Paula Cole",
    @"David Cook",
    @"Billy Corgan",
    @"Jerome Courtland",
    @"Wayne Coyne",
    @"Christopher Cross",
    @"Sheryl Crow",
    @"Rivers Cuomo",
    @"Ken Curtis",
    @"Billy Ray Cyrus",
    @"Dalia",
    @"Clifton Davis",
    @"Sammy Davis, Jr.",
    @"Doris Day",
    @"Zack de la Rocha",
    @"Donna De Lory",
    @"Fernando del Valle",
    @"Tom DeLonge",
    @"Cheri Dennis",
    @"Zooey Deschanel",
    @"Karla DeVito",
    @"Marlene Dietrich",
    @"Ronnie James Dio",
    @"Divine",
    @"Nate Dogg",
    @"Vinnie Dombroski",
    @"Mike Doughty",
    @"Kevin DuBrow",
    @"Fred Durst",
    @"Bob Dylan",
    @"Linda Eder",
    @"Bobby Edner",
    @"Missy Elliott",
    @"Mark Erelli",
    @"Melissa Etheridge",
    @"Faith Evans",
    @"Terry Evans",
    @"Blake McIver Ewing",
    @"Five for Fighting",
        @"Ella Fitzgerald",
        @"John Fogerty",
        @"Ben Folds",
        @"Bruce Ford",
        @"Aretha Franklin",
        @"Dennis Frederiksen",
        @"Annette Funicello",
        @"Judy Garland",
        @"Marvin Gaye",
        @"Julia Gerity",
        @"Ben Gibbard",
        @"Terri Gibbs",
        @"Gibson Brothers",
        @"Kathie Lee Gifford",
        @"Louise Goffin",
        @"Whoopi Goldberg",
        @"Ida Goodson",
        @"Jay Gordon",
        @"Laura Jane Grace",
        @"Tammy Hansen Grady",
        @"Denyce Graves",
        @"Lee Greenwood",
        @"Dave Grohl",
        @"Sammy Hagar",
        @"Anthony Hamilton",
        @"H cont.",
        @"Linda Hargrove",
        @"Sam Harris",
        @"Debbie Harry",
        @"Hunter Hayes",
        @"Jimi Hendri",
        @"James Hetfield",
        @"Nick Hexum",
        @"Taylor Hicks",
        @"Faith Hill",
        @"Billie Holiday",
        @"David Holliday",
        @"Jennifer Holliday",
        @"Loleatta Holloway",
        @"Shannon Hoon",
        @"Linda Hopper",
        @"Mark Hoppus",
        @"Whitney Houston",
        @"Nancy Hower",
        @"Janis Ian",
        @"Ronald Isley",
        @"Janet Jackson",
        @"Michael Jackson",
        @"Walter Jackson",
        @"Jandek",
        @"Jenny O.",
        @"Joan Jett",
        @"Jewel",
        @"Billy Joel",
        @"Jack Johnson",
        @"Janis Joplin",
        @"Chris Kelly",
        @"Myles Kennedy",
        @"Alicia Keys",
        @"E.G. Kight",
        @"Carole King",
        @"Jonathan Knight",
        @"Marie Knight",
        @"Ed Kowalczyk",
        @"Jennie Kwan",
        @"Lane Sisters",
        @"Jani Lane",
        @"Jonny Lang",
        @"Frances Langford",
        @"Angela Lansbury",
        @"Mario Lanza",
        @"Cyndi Lauper",
        @"Jamie Laurie",
        @"Debra Laws",
        @"Eloise Laws",
        @"Jerry Lawson",
        @"Steve Leeds",
        @"Legendary Stardust Cowboy",
        @"Liberace",
        @"Lil Wayne",
        @"Lloyd",
        @"Lobo",
        @"Claudine Longet",
        @"Lisa Lopes",
        @"Bobby Lord",
        @"Courtney Love",
        @"Scott Lucas",
        @"Rebecca Luker",
        @"Barbara Lyon",
        @"Madonna",
        @"Ann Magnuson",
        @"Barbara Mandrell",
        @"Irene Manning",
        @"Marilyn Manson",
        @"Dean Martin",
        @"Kevin Martin",
        @"Marvis Martin",
        @"Mary Martin",
        @"Ricky Martin",
        @"Mashonda",
        @"Al Matthews",
        @"Dave Matthews",
        @"Maxwell",
        @"Curtis Mayfield",
        @"MC Hammer",
        @"Edwin McCain",
        @"Ed McCaskey",
        @"Lisa McClowry",
        @"Donnie McClurkin",
        @"Paul McCoy",
        @"Bert McCracken",
        @"Gwen McCrae",
        @"Mindy McCready",
        @"Reba McEntire",
        @"Duff McKagan",
        @"Don McLean",
        @"Meat Loaf",
        @"Travis Meeks",
        @"James Melton",
        @"Susanne Mentzer",
        @"Ethel Merman",
        @"Bret Michaels",
        @"Miguel",
        @"Ezra Miller",
        @"Liza Minnelli",
        @"Patrick Monahan",
        @"Monica",
        @"Marilyn Monroe",
        @"Susan Moonsie",
        @"Abra Moore",
        @"Mandy Moore",
        @"David Morris",
        @"Jim Morrison",
        @"Rick Moses",
        @"Malina Moye",
        @"Rich Mullins",
        @"Dave Mustaine",
        @"Jim Nabors",
        @"Vince Neil",
        @"Herva Nelli",
        @"Stevie Nicks",
        @"Angela Nicoletti",
        @"Elena Nikolaidi",
        @"Bradley Nowell",
        @"Benjamin Orr",
        @"Johnny Otis",
        @"Bárbara Padilla",
        @"Tommy Page",
        @"Aleksa Palladino",
        @"Amanda Palmer",
        @"Dolly Parton",
        @"P cont.",
        @"Richard Patrick",
        @"Sandi Patty",
        @"Tom Petty",
        @"Kate Pierson",
        @"Landon Pigg",
        @"Pink",
        @"Jada Pinkett Smith",
        @"Tomata du Plenty",
        @"John Popper",
        @"Billy Porter",
        @"Dick Powell",
        @"Elvis Presley",
        @"Billy Preston",
        @"Prince",
        @"Seth Putnam",
        @"Qwel",
        @"Bonnie Raitt",
        @"Raven-Symoné",
        @"Sydney Rayner",
        @"Jay Reatard",
        @"Lou Reed",
        @"Dana Reeve",
        @"Rell",
        @"Pat Renella",
        @"Malvina Reynolds",
        @"Trent Reznor",
        @"LeAnn Rimes",
        @"Marty Robbins",
        @"Sixto Rodriguez",
        @"Rogue",
        @"Ed Roland",
        @"Linda Ronstadt",
        @"Axl Rose",
        @"Kelly Rowland",
        @"Nate Ruess",
        @"Mason Ruffner",
        @"Jack Russell",
        @"Tony Saletan",
        @"Mark Sandman",
        @"Bambi Lee Savage",
        @"Wes Scantlin",
        @"Fred Schneider",
        @"Diane Schuur",
        @"Michael Sembello",
        @"Tupac Shakur",
        @"Shana",
        @"Wini Shaw",
        @"Duncan Sheik",
        @"Frank Sinatra",
        @"Doris Singleton",
        @"Allison Smith",
        @"Chris Smith",
        @"Elliott Smith",
        @"Michael W. Smith",
        @"Will Smith",
        @"Oley Speaks",
        @"Britney Spears",
        @"Benny Spellman",
        @"Layne Staley",
        @"Gwen Stefani",
        @"S cont.",
        @"Risë Stevens",
        @"Michael Stipe",
        @"Rose Stone",
        @"Vet Stone",
        @"J.D. Stooks",
        @"Izzy Stradlin",
        @"Peter Stuart",
        @"Chuck Suchy",
        @"Donna Summer",
        @"Keith Sweat",
        @"Matthew Sweet",
        @"Norma Tanega",
        @"James Taylor",
        @"Shooby Taylor",
        @"Shirley Temple",
        @"Robin Thicke",
        @"B. J. Thomas",
        @"Carla Thomas",
        @"Rob Thomas",
        @"George Thorogood",
        @"Tiffany",
        @"Justin Timberlake",
        @"Aaron Tippin",
        @"Chris Tomlin",
        @"Tina Turner",
        @"Bobby V",
        @"Ritchie Valens",
        @"Frankie Valli",
        @"Dick Van Dyke",
        @"Donnie Van Zant",
        @"Johnny Van Zant",
        @"Ronnie Van Zant",
        @"Brian Vander Ark",
        @"John Vanderslice",
        @"Eddie Vedder",
        @"Albertina Walker",
        @"Tim Weed",
        @"Scott Weiland",
        @"Richard Wentworth",
        @"Barbara Werle",
        @"Floyd Red Crow Westerman",
        @"Jack White",
        @"Slim Whitman",
        @"Jackie Wilson",
        @"Tim Wilson",
        @"Iva Withers",
        @"Herbert Witherspoon",
        @"Darren Keith Woods",
        @"Betty Wright",
        @"Chely Wright",
        @"Curtis Wright",
        @"Dave Wyndorf",
        @"Weird Al Yankovic",
        @"Vicki Yohe",
        @"Stella Zambalis",
        @"Robin Zander",
        @"Frank Zappa",
        @"Rob Zombie",
    @"Natalia Zukerman",nil];
    
    
    
    
    self.movieCategory = [[NSMutableArray alloc] initWithObjects: @"Ninja Turtles", @"Rush Hour",@"007",@"Aladdin",@"Argo",@"Avatar",@"Babel",@"Bambi",@"Batman",@"Black Hawk Down",@"The Book of Eli",@"Bounce",@"The Bourne Identity",@"Cars",@"Cast Away",@"Catch Me if You Can",@"Catwoman",@"Cinderella",@"Cowboys and Aliens",@"Coyote Ugly",@"The Da Vinci Code",@"Daredevil",@"Day After Tomorrow",@"Dirty Dancing",@"District 9",@"Django",@"Dodgeball",@"Dumbo",@"Fantastic Four",@"Fast and the Furious",@"Fifth Element",@"Fight Club",@"Final Destination",@"Finding Nemo",@"Full Metal Jacket", @"Ghost Rider",@"Gladiator",@"Green Zone",@"Hangover",@"Hangover 3",@"Happy Feet",@"Harry Potter",@"Hitch", @"I am Legend",@"I, Robot",@"Ice Age",@"Inception",@"Iron Man",@"Italian Job",@"Jarhead",@"King Arthur",@"Les Misérables",@"Lion King",@"Lord of the Rings",@"Mary Poppins",@"Matrix",@"Million Dollar Baby",@"Mission: Impossible",@"Monster Inc.",@"Mr. and Mrs. Smith",@"Mulan",@"My Super Ex-Girlfriend",@"Narnia",@"Next",@"Ocean's 11",@"P.S. – I Love You",@"The Godfather",@"Pinocchio",@"Pirates of the Caribbean",@"Pitch Black",@"Ratatouille",@"Resident Evil",@"Rio",@"Robin Hood",@"Romeo + Juliet",@"S.W.A.T.",@"Safe House",@"Shaft",@"Shooter",@"Shrek", @"Shutter Island",@"Signs",@"Silent Hill",@"Spider-Man",@"Star Wars I",@"Step up",@"Super 8",@"Superman",@"Sweet Home Alabama",@"Terminator",@"Timeline",@"Titanic", @"Tomb Raider",@"Troy",@"Twilight",@"Unbreakable",@"Van Helsing",@"Wall-E",@"Toy Story",@"Life of Pi",@"Lincoln",
                          @"Zero Dark Thirty",
                          @"The Intouchables",
                          @"The Muppets",
                          @"Wild Bill",
                          @"Moonrise Kingdom",
                          @"Django",
                          @"Silver Linings Playbook",
                          @"Beasts of the Southern Wild",
                          @"The Hobbit",
                          @"Marley",
                          @"The Wolverine",
                          @"The Shawshank Redemption",
                          @"Goodfellas",
                          @"Forrest Gump",
                          @"The Lone Ranger",
                          @"World War Z",
                          @"The Transporter",
                          @"Oblivion",
                          @"G.I. Joe",
                          @"Man of Steel",
                          @"The Terminator",
                          @"Jurassic Park",
                          @"Fantastic Mr. Fox",
                          @"Big Momma's House",
                          @"Suits",
                          @"The Dark Knight",
                          @"Despicable Me",
                          @"Sherlock Holmes",
                          @"Men in Black",
                          @"Green Lantern",
                          @"American Gangster",
                          @"Yes Man",
                          @"Madagascar",
                          @"The Lorax",
                          @"Bolt",
                          @"Bad Boys",
                          @"The Green Hornet",
                          @"Beverly Hills Cop",
                          @"Chicken Run",
                          @"The Simpsons Movie",
                          @"Cloudy with a Chance of Meatballs", nil];
    
    
    
    
    
    //Build a new Array with the random objects
    self.resultArray = [[NSMutableArray alloc] init];
    
    // Build temporary array - we will randomly remove one element from here
    // and add it to our resultArray
    NSMutableArray *tempArray = [[NSMutableArray alloc] init];
  
    NSMutableArray *varArray;
    if ([self.category isEqualToString:@"Movies"]) {
        varArray = [NSMutableArray arrayWithArray:self.movieCategory];
        categoryCounter=0;
        self.radioCounter.currentPage = 0;
    }else if ([self.category isEqualToString:@"Singers"])
    {         varArray = [NSMutableArray arrayWithArray:self.singersCategory];
        categoryCounter=1;
        self.radioCounter.currentPage = 1;
    }else if ([self.category isEqualToString:@"Celebs"])
    {         varArray = [NSMutableArray arrayWithArray:self.celebsCategory];
        categoryCounter=2;
        self.radioCounter.currentPage = 2;
    }else if ([self.category isEqualToString:@"Shows"])
    {         varArray = [NSMutableArray arrayWithArray:self.showsCategory];
        categoryCounter=3;
        self.radioCounter.currentPage = 3;
    }
    else{
        varArray = [NSMutableArray arrayWithArray:self.randomCategories];
self.currentCategory.text = @"Random";
        categoryCounter=4;
        self.radioCounter.currentPage = 4;
    }
    
    
    for(int x = 0; x < [varArray count]; x++)
    {
        [tempArray addObject:varArray[x]];
    }
    
    for(int x = 0; x < [varArray count]; x++)
    {
        // Get Random element from tempArray
        NSInteger n = (arc4random() % [tempArray count]);
        id arrayElement = tempArray[n];
        
        // Add Random element to Result
        [self.resultArray addObject:arrayElement];
        // Remove from tempArray (as we added the object to the result array)
        [tempArray removeObjectAtIndex:n];
    }
    
    self.CategoryLabel.text =self.resultArray[0];
    
   }

- (void) next{
    //NSLog(@"array count: %  counter: %d",[self.resultArray count], counter);
    counter++;
   
    if (counter<[self.resultArray count]) {
        self.CategoryLabel.text = self.resultArray[counter];
 }
    else {
     counter=0;
     self.CategoryLabel.text = self.resultArray[counter];
 }
    [self swipeEffectForItemBack];

 }


-(void) goBackItemInCategory{
    counter--;
    
    if (counter<0) {
        
        counter =[self.resultArray count]-1;
        self.CategoryLabel.text=self.resultArray[counter];
    } else if (counter ==0){
        self.CategoryLabel.text=self.resultArray[0];
    }else{
        self.CategoryLabel.text=self.resultArray[counter];
    }
    [self.CategoryLabel setFont:[UIFont systemFontOfSize:[self stringLength]]];
    [self swipeEffectForItemNext];
}


- (int)stringLength{
    if ([self.resultArray[counter] length]>= 20) {
        
        return 30;
    } else{
        [self.CategoryLabel setFont:[UIFont systemFontOfSize:45]];
        return 30;
    }
    
}


- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (IBAction)nextButton:(id)sender {
    [self next];
    
}

- (IBAction)backButton:(id)sender {
    CharadesViewController *HomeView = [self.storyboard instantiateViewControllerWithIdentifier:@"home"];
    
    [self.navigationController pushViewController:HomeView animated:YES];
    [self presentViewController:HomeView animated:YES completion:nil];
}

- (IBAction)nextCategory:(id)sender {
    
    [self goNextItemInCategory];
}

- (IBAction)categorySwipe:(UISwipeGestureRecognizer *)sender {
    [self goNextItemInCategory];
    }


- (IBAction)itemSwipTouchEffect:(UITapGestureRecognizer *)sender{
     [self next];
}

- (IBAction)itemCategoryTouchEffect:(UITapGestureRecognizer *)sender{
    [self goNextItemInCategory];
}

-(void) goNextItemInCategory{
   
    categoryCounter++;
    
    if (categoryCounter<[self.categories count]) {
        self.category = self.categories[categoryCounter];
        //self.currentCategory.text = self.category;
        
    }
    
    else {
        categoryCounter=0;
        self.category = self.categories[categoryCounter];
        //self.currentCategory.text = self.category;
        
    }
    [self StartArray];

    [self swipeEffectForCategoryNext];
    
counter=0;
}

-(void) swipeEffectForCategoryBack{
    NSString *newText;
    UILabel  *existingLabel = self.currentCategory;
    
    newText = self.categories[categoryCounter];
    
    // animate the sliding of them into place
    
    [UIView transitionWithView:existingLabel
                      duration:0.5
                       options:UIViewAnimationOptionTransitionFlipFromBottom
                    animations:^{
                        existingLabel.text = newText;
                    }
                    completion:nil];

}

-(void) swipeEffectForCategoryNext{
    NSString *newText;
    UILabel  *existingLabel = self.currentCategory;
    
    newText = self.category;
    
    // animate the sliding of them into place
    
    [UIView transitionWithView:existingLabel
                      duration:0.5
                       options:UIViewAnimationOptionTransitionFlipFromTop
                    animations:^{
                        existingLabel.text = newText;
                    }
                    completion:nil];
    
}

-(void) swipeEffectForItemNext{
    NSString *newText;
    UILabel  *existingLabel = self.CategoryLabel;
    
    newText = self.resultArray[counter];
    
    // animate the sliding of them into place
    
    [UIView transitionWithView:existingLabel
                      duration:0.5
                       options:UIViewAnimationOptionTransitionFlipFromTop
                    animations:^{
                        existingLabel.text = newText;
                    }
                    completion:nil];
    
    
}
-(void) swipeEffectForItemBack{
    NSString *newText;
    UILabel  *existingLabel = self.CategoryLabel;
    
    newText = self.resultArray[counter];
    
    // animate the sliding of them into place
    
    [UIView transitionWithView:existingLabel
                      duration:0.5
                       options:UIViewAnimationOptionTransitionFlipFromBottom
                    animations:^{
                        existingLabel.text = newText;
                    }
                    completion:nil];
    
    
}

-(void) goBackCategory{
    categoryCounter--;
    
    if (categoryCounter<0) {
        
        categoryCounter = [self.categories count]-1;
        self.category = self.categories[categoryCounter];
       // self.currentCategory.text=self.categories[categoryCounter];
    }  else{
        self.category = self.categories[categoryCounter];
       // self.currentCategory.text=self.categories[categoryCounter];
    }
    [self swipeEffectForCategoryBack];
    [self StartArray];
}



- (IBAction)itemSwipRight:(UISwipeGestureRecognizer *)recognizer{
    [self goBackItemInCategory];
}

- (IBAction)previousButton:(id)sender {
    [self goBackItemInCategory];
}

- (IBAction)backCategory:(id)sender {
    [self goBackCategory];

}
- (IBAction)startButton:(id)sender {
    
    Store *whatTeamIsUp = [Store sharedStore];
    
    if (team ==YES) {
        team = NO;
        whatTeamIsUp.Team = @"Team B's Turn";
    }else {
        whatTeamIsUp.Team = @"Team A's Turn";
        team=YES;}
    
}

- (IBAction)itemSwip:(UISwipeGestureRecognizer *)recognizer{
    [self next];
}
- (IBAction)categorySwipeRight:(UISwipeGestureRecognizer *)sender{
    [self goBackCategory];
}


- (IBAction)scoreButton:(id)sender {
    SampleSheetViewController *svc = [[SampleSheetViewController alloc] init];
   
    self.PopUpForScore =svc;
   //Gets the variable from Store Class for the Teams
    Store* myStore = [Store sharedStore];
    
   //Populates the score
    NSLog(@"%@",myStore.TeamA);
    
    PopUpForScore.teamBscoreLabel.text= myStore.TeamB;
    
    if(!myStore.TeamA||(myStore.TeamA.length==0)){
       PopUpForScore.teamAscoreLabel.text =@"0";
    }else{
        PopUpForScore.teamAscoreLabel.text= myStore.TeamA;
    }
    
    if(!myStore.TeamB||(myStore.TeamB.length==0)){
        PopUpForScore.teamBscoreLabel.text =@"0";
    }else{
        PopUpForScore.teamBscoreLabel.text= myStore.TeamB;
    }
    
    NAModalSheet *sheet = [[NAModalSheet alloc] initWithViewController:svc presentationStyle:NAModalSheetPresentationStyleFadeInCentered];
    sheet.cornerRadiusWhenCentered = 24.0;
    sheet.delegate = self;
    svc.modalSheet = sheet;
    
    [sheet presentWithCompletion:^{
        
    }];
}

- (void)modalSheetTouchedOutsideContent:(NAModalSheet *)sheet
{
    [sheet dismissWithCompletion:^{
            
        }];
    
}
- (IBAction)hideTourView:(id)sender {
    self.tourView.hidden = YES;
}
@end
